ALTER TABLE batches
    ADD COLUMN IF NOT EXISTS expiry_date DATE,
    ADD COLUMN IF NOT EXISTS grade VARCHAR(1) NOT NULL DEFAULT 'A',
    ADD COLUMN IF NOT EXISTS warehouse_id BIGINT REFERENCES warehouses(id);
