-- Drop the check constraint from V21
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_action_check;

-- Re-create the check constraint with the new disposal and return actions
ALTER TABLE audit_logs
    ADD CONSTRAINT audit_logs_action_check
    CHECK (action IN (
        'LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'STATUS_CHANGE', 'APPROVE', 'REJECT', 'CANCEL', 'SOFT_DELETE', 'ASSIGN', 'UNASSIGN',
        'RECEIPT_APPROVE', 'RECEIPT_REJECT', 'RECEIPT_RETURN_CONFIRM', 'RECEIPT_PUTAWAY_COMPLETE',
        'QUARANTINE_RTV_CREATE', 'QUARANTINE_RTV_CONFIRM', 'INVENTORY_UPDATE',
        'TRANSFER_CREATE', 'TRANSFER_UPDATE', 'TRANSFER_APPROVE', 'TRANSFER_REJECT', 'TRANSFER_TRIP_ASSIGN', 'TRANSFER_SHIP', 'TRANSFER_DEPART', 'TRANSFER_RECEIVE_COUNT', 'TRANSFER_RECEIVE_CONFIRM', 'TRANSFER_DISCREPANCY_CREATE', 'TRANSFER_CANCEL',
        'BILLING_NOTIFICATION_CREATE', 'BILLING_NOTIFICATION_READ',
        'RECEIPT_QC_SUBMIT', 'RECEIPT_QC_CONFIRM',
        'QUARANTINE_DISPOSAL_CREATE', 'QUARANTINE_DISPOSAL_APPROVE', 'CREDIT_NOTE_CREATE',
        'TRANSFER_FINAL_RECEIVE', 'TRANSFER_UNSHIP', 'TRANSFER_RECEIVE_CHECK'
    ));
