-- V32: Add missing STOCKTAKE audit actions to constraint
-- Supabase may have an older V25 that didn't include stocktake actions
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_action_check;
ALTER TABLE audit_logs
    ADD CONSTRAINT audit_logs_action_check
    CHECK (action IN (
        'LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'STATUS_CHANGE', 'APPROVE', 'REJECT',
        'CANCEL', 'SOFT_DELETE', 'ASSIGN', 'UNASSIGN',
        'RECEIPT_APPROVE', 'RECEIPT_REJECT', 'RECEIPT_RETURN_CONFIRM', 'RECEIPT_PUTAWAY_COMPLETE',
        'QUARANTINE_RTV_CREATE', 'QUARANTINE_RTV_CONFIRM',
        'QUARANTINE_DISPOSAL_CREATE', 'QUARANTINE_DISPOSAL_APPROVE',
        'INVENTORY_UPDATE',
        'TRANSFER_CREATE', 'TRANSFER_UPDATE', 'TRANSFER_APPROVE', 'TRANSFER_REJECT',
        'TRANSFER_TRIP_ASSIGN', 'TRANSFER_SHIP', 'TRANSFER_DEPART',
        'TRANSFER_RECEIVE_CHECK', 'TRANSFER_RECEIVE_COUNT', 'TRANSFER_RECEIVE_CONFIRM',
        'TRANSFER_FINAL_RECEIVE', 'TRANSFER_UNSHIP',
        'TRANSFER_DISCREPANCY_CREATE', 'TRANSFER_CANCEL',
        'BILLING_NOTIFICATION_CREATE', 'BILLING_NOTIFICATION_READ',
        'CREDIT_NOTE_CREATE',
        'RECEIPT_QC_SUBMIT', 'RECEIPT_QC_CONFIRM',
        'STOCKTAKE_CREATE', 'STOCKTAKE_START', 'STOCKTAKE_COUNT_UPDATE',
        'STOCKTAKE_COMPLETE', 'STOCKTAKE_AUTO_APPROVE', 'STOCKTAKE_APPROVE',
        'STOCKTAKE_REJECT', 'STOCKTAKE_CANCEL',
        'DELIVERY_ORDER_CREATE', 'DELIVERY_ORDER_APPROVE', 'DELIVERY_ORDER_CANCEL',
        'DELIVERY_ORDER_COMPLETE', 'TRIP_CREATE', 'TRIP_DEPART', 'TRIP_COMPLETE',
        'PRICE_LIST_CREATE', 'PRICE_LIST_UPDATE', 'PRICE_LIST_APPROVE',
        'INVOICE_CREATE', 'PAYMENT_CREATE', 'CREDIT_NOTE_APPROVE'
    )) NOT VALID;
