-- Drop the restricted audit logs action check constraint
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_action_check;

-- Re-create the check constraint with the updated AuditAction enum values including StockTake and all Transfer flows
ALTER TABLE audit_logs
    ADD CONSTRAINT audit_logs_action_check
    CHECK (action IN (
        'LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'STATUS_CHANGE', 'APPROVE', 'REJECT', 'CANCEL', 'SOFT_DELETE', 'ASSIGN', 'UNASSIGN',
        'RECEIPT_CREATE', 'RECEIPT_RECEIVE', 'RECEIPT_APPROVE', 'RECEIPT_APPROVED', 'RECEIPT_REJECT', 'RECEIPT_REJECTED', 'RECEIPT_RETURN_CONFIRM', 'RECEIPT_PUTAWAY_COMPLETE', 'RECEIPT_QC_SUBMIT', 'RECEIPT_QC_CONFIRM',
        'QUARANTINE_RTV_CREATE', 'QUARANTINE_RTV_CONFIRM', 'INVENTORY_UPDATE',
        'TRANSFER_CREATE', 'TRANSFER_UPDATE', 'TRANSFER_APPROVE', 'TRANSFER_REJECT', 'TRANSFER_TRIP_ASSIGN', 'TRANSFER_SHIP', 'TRANSFER_UNSHIP', 'TRANSFER_DEPART', 'TRANSFER_RECEIVE_COUNT', 'TRANSFER_RECEIVE_CHECK', 'TRANSFER_RECEIVE_CONFIRM', 'TRANSFER_FINAL_RECEIVE', 'TRANSFER_DISCREPANCY_CREATE', 'TRANSFER_CANCEL',
        'BILLING_NOTIFICATION_CREATE', 'BILLING_NOTIFICATION_READ',
        'STOCKTAKE_CREATE', 'STOCKTAKE_START', 'STOCKTAKE_COUNT_UPDATE', 'STOCKTAKE_COMPLETE', 'STOCKTAKE_APPROVE', 'STOCKTAKE_REJECT', 'STOCKTAKE_CANCEL', 'STOCKTAKE_AUTO_APPROVE'
    ));
