-- 1. Rename Tables
ALTER TABLE transfers RENAME TO inter_warehouse_transfers;
ALTER TABLE transfer_items RENAME TO inter_warehouse_transfer_items;
ALTER TABLE transfer_allocations RENAME TO inter_warehouse_transfer_allocations;

-- 2. Rename Sequences
ALTER SEQUENCE transfers_id_seq RENAME TO inter_warehouse_transfers_id_seq;
ALTER SEQUENCE transfer_items_id_seq RENAME TO inter_warehouse_transfer_items_id_seq;
ALTER SEQUENCE transfer_allocations_id_seq RENAME TO inter_warehouse_transfer_allocations_id_seq;

-- 3. Rename Constraints (This automatically renames primary key and unique key indexes)
-- inter_warehouse_transfers constraints
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_pkey TO inter_warehouse_transfers_pkey;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_transfer_number_key TO inter_warehouse_transfers_transfer_number_key;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_status_check TO inter_warehouse_transfers_status_check;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_accounting_period_id_fkey TO inter_warehouse_transfers_accounting_period_id_fkey;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_approved_by_fkey TO inter_warehouse_transfers_approved_by_fkey;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_confirmed_by_fkey TO inter_warehouse_transfers_confirmed_by_fkey;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_created_by_fkey TO inter_warehouse_transfers_created_by_fkey;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_destination_warehouse_id_fkey TO inter_warehouse_transfers_destination_warehouse_id_fkey;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_rejected_by_fkey TO inter_warehouse_transfers_rejected_by_fkey;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_source_warehouse_id_fkey TO inter_warehouse_transfers_source_warehouse_id_fkey;
ALTER TABLE inter_warehouse_transfers RENAME CONSTRAINT transfers_trip_id_fkey TO inter_warehouse_transfers_trip_id_fkey;

-- inter_warehouse_transfer_items constraints
ALTER TABLE inter_warehouse_transfer_items RENAME CONSTRAINT transfer_items_pkey TO inter_warehouse_transfer_items_pkey;
ALTER TABLE inter_warehouse_transfer_items RENAME CONSTRAINT transfer_items_transfer_id_fkey TO inter_warehouse_transfer_items_transfer_id_fkey;
ALTER TABLE inter_warehouse_transfer_items RENAME CONSTRAINT transfer_items_batch_id_fkey TO inter_warehouse_transfer_items_batch_id_fkey;
ALTER TABLE inter_warehouse_transfer_items RENAME CONSTRAINT transfer_items_checked_by_fkey TO inter_warehouse_transfer_items_checked_by_fkey;
ALTER TABLE inter_warehouse_transfer_items RENAME CONSTRAINT transfer_items_destination_location_id_fkey TO inter_warehouse_transfer_items_destination_location_id_fkey;
ALTER TABLE inter_warehouse_transfer_items RENAME CONSTRAINT transfer_items_product_id_fkey TO inter_warehouse_transfer_items_product_id_fkey;
ALTER TABLE inter_warehouse_transfer_items RENAME CONSTRAINT transfer_items_qc_result_check TO inter_warehouse_transfer_items_qc_result_check;
ALTER TABLE inter_warehouse_transfer_items RENAME CONSTRAINT transfer_items_source_location_id_fkey TO inter_warehouse_transfer_items_source_location_id_fkey;

-- inter_warehouse_transfer_allocations constraints
ALTER TABLE inter_warehouse_transfer_allocations RENAME CONSTRAINT transfer_allocations_pkey TO inter_warehouse_transfer_allocations_pkey;
ALTER TABLE inter_warehouse_transfer_allocations RENAME CONSTRAINT transfer_allocations_allocated_qty_check TO inter_warehouse_transfer_allocations_allocated_qty_check;
ALTER TABLE inter_warehouse_transfer_allocations RENAME CONSTRAINT transfer_allocations_inventory_id_fkey TO inter_warehouse_transfer_allocations_inventory_id_fkey;
ALTER TABLE inter_warehouse_transfer_allocations RENAME CONSTRAINT transfer_allocations_transfer_item_id_fkey TO inter_warehouse_transfer_allocations_transfer_item_id_fkey;
ALTER TABLE inter_warehouse_transfer_allocations RENAME CONSTRAINT transfer_allocations_transfer_item_id_inventory_id_key TO inter_warehouse_transfer_allocations_item_inventory_unique;

-- 4. Rename Plain/Unique Indexes (which are not constraints)
ALTER INDEX idx_transfers_src_status RENAME TO idx_inter_warehouse_transfers_src_status;
ALTER INDEX ux_transfers_trip_id RENAME TO ux_inter_warehouse_transfers_trip_id;
ALTER INDEX uq_transfers_external_instruction_active RENAME TO uq_inter_warehouse_transfers_external_instruction_active;
