-- =============================================================================
-- V45: Sync chk_audit_logs_action constraint with AuditAction enum
-- =============================================================================
-- Context:
--   Commit 8b390f6a added 8 new AuditAction constants and a corresponding
--   migration (V47 in that branch), but the migration was not merged into
--   this branch while audit_log rows with those actions already exist in DB.
--   This migration re-creates the CHECK constraint to include all current
--   enum constants, preventing Hibernate IllegalArgumentException on read.
--
-- New constants added:
--   RECEIPT_PARTIAL_APPROVE, RECEIPT_PRE_RECEIVE_APPROVE,
--   RECEIPT_PRE_RECEIVE_REJECT, RECEIPT_PRE_RECEIVE_RESUBMIT,
--   RECEIPT_RECEIVE, RECEIPT_CANCEL, RECEIPT_REOPEN, RECEIPT_CORRECTION
-- =============================================================================

-- Drop the existing constraint (idempotent via IF EXISTS)
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS chk_audit_logs_action;

-- Re-create with the full set of current AuditAction enum constants
ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_action CHECK (action IN (
    'LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'STATUS_CHANGE', 'APPROVE', 'REJECT', 'CANCEL', 'SOFT_DELETE', 'ASSIGN',
    'UNASSIGN', 'UPLOAD_POD', 'REQUEST_OTP', 'CONFIRM_DELIVERY', 'RESET_DELIVERY_OTP', 'FAIL_DELIVERY',
    'TRIP_CREATE', 'TRIP_UPDATE', 'TRIP_CANCEL', 'TRIP_DEPART', 'DELIVERY_ATTEMPT_CREATE', 'COMPLETE_TRIP',
    'PICKING_PLAN_SAVE', 'PICKED_GOODS_RETURN_TO_BIN', 'PICKING_REPLACEMENT_SAVE', 'DELIVERY_ORDER_PICK_COMPLETE',
    'DELIVERY_ORDER_UPDATE',
    'OUTBOUND_QC_FAIL_QUARANTINE', 'DELIVERY_ORDER_QC_APPROVE', 'DELIVERY_ORDER_WAREHOUSE_APPROVE',
    'DELIVERY_ORDER_WAREHOUSE_REJECT', 'RETURN_FLOW_RECEIVE_CONFIRM', 'RETURN_FLOW_COUNT_QC_SUBMIT',
    'RETURN_FLOW_QC_ACCEPT', 'RETURN_FLOW_QC_REJECT', 'RETURN_FLOW_PUTAWAY_PLAN', 'RETURN_FLOW_PUTAWAY_COMPLETE',
    'INVOICE_AUTO_CREATE', 'RECEIPT_RETURN_CONFIRM', 'RECEIPT_REJECT', 'RECEIPT_APPROVE', 'RECEIPT_PARTIAL_APPROVE',
    'QUARANTINE_RTV_CREATE', 'QUARANTINE_RTV_CONFIRM', 'RECEIPT_QC_CONFIRM', 'RECEIPT_QC_SUBMIT',
    'RECEIPT_PUTAWAY_COMPLETE', 'INVENTORY_UPDATE', 'TRANSFER_APPROVE', 'TRANSFER_DEPART', 'TRANSFER_UNSHIP',
    'TRANSFER_SHIP', 'TRANSFER_TRIP_ASSIGN', 'TRANSFER_SOURCE_LOAD_REPORT', 'TRANSFER_SOURCE_LOAD_REWORK',
    'TRANSFER_DISCREPANCY_CREATE', 'TRANSFER_RETURN_TO_SOURCE', 'TRANSFER_QUARANTINE_REJECT',
    'TRANSFER_FINAL_RECEIVE', 'TRANSFER_RECEIVE_CHECK', 'TRANSFER_RECEIVE_COUNT', 'TRANSFER_CANCEL',
    'TRANSFER_REJECT', 'STOCKTAKE_CANCEL', 'STOCKTAKE_REJECT', 'STOCKTAKE_APPROVE', 'STOCKTAKE_COMPLETE',
    'STOCKTAKE_AUTO_APPROVE', 'STOCKTAKE_COUNT_UPDATE', 'STOCKTAKE_START', 'STOCKTAKE_CREATE', 'PRICE_IMPORT',
    'PRICE_APPROVE', 'PRICE_CANCEL', 'PRICE_UPDATE', 'PRICE_CREATE', 'RECEIPT_CREATE',
    'RECEIPT_PRE_RECEIVE_APPROVE', 'RECEIPT_PRE_RECEIVE_REJECT', 'RECEIPT_PRE_RECEIVE_RESUBMIT',
    'RECEIPT_RECEIVE', 'RECEIPT_CANCEL', 'RECEIPT_REOPEN', 'RECEIPT_CORRECTION',
    'CREDIT_NOTE_CREATE', 'QUARANTINE_DISPOSAL_CREATE', 'QUARANTINE_DISPOSAL_APPROVE', 'VIEW_REPORT',
    'TRANSFER_REQUEST_CREATE', 'TRANSFER_REQUEST_UPDATE', 'TRANSFER_REQUEST_SUBMIT',
    'TRANSFER_REQUEST_CEO_APPROVE', 'TRANSFER_REQUEST_CEO_REJECT', 'TRANSFER_REQUEST_CONVERT',
    'TRANSFER_OUTBOUND_QC', 'TRANSFER_LOAD_HANDOVER', 'TRANSFER_ARRIVE', 'TRANSFER_ARRIVAL_HANDOVER',
    'TRANSFER_RETURN_DEPART', 'TRANSFER_RETURN_ARRIVE', 'TRANSFER_RETURN_HANDOVER',
    'CORRECTION_VOUCHER_CREATE'
));
