ALTER TABLE receipts DROP CONSTRAINT IF EXISTS receipts_status_check;

ALTER TABLE receipts
    ADD CONSTRAINT receipts_status_check CHECK (status IN (
        'PENDING_MANAGER_APPROVAL',
        'REVISION_REQUIRED',
        'PENDING_RECEIPT',
        'DRAFT',
        'QC_COMPLETED',
        'QC_FAILED',
        'APPROVED',
        'PARTIALLY_APPROVED',
        'PUTAWAY_COMPLETED',
        'RETURN_TO_SUPPLIER_PENDING',
        'RETURNED_TO_SUPPLIER',
        'CANCELLED'
    ));

ALTER TABLE receipt_items
    ADD COLUMN IF NOT EXISTS quality_passed_qty INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS quality_failed_qty INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS approved_qty INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS quarantine_ready_qty INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS quarantine_qty INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS resolved_quarantine_qty INTEGER NOT NULL DEFAULT 0;

ALTER TABLE receipt_items
    DROP CONSTRAINT IF EXISTS chk_receipt_items_spec003_quantities,
    ADD CONSTRAINT chk_receipt_items_spec003_quantities CHECK (
        quality_passed_qty >= 0
        AND quality_failed_qty >= 0
        AND approved_qty >= 0
        AND quarantine_ready_qty >= 0
        AND quarantine_qty >= 0
        AND resolved_quarantine_qty >= 0
        AND resolved_quarantine_qty <= quarantine_qty
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_receipts_active_source
    ON receipts (supplier_id, warehouse_id, source_order_code, type)
    WHERE status NOT IN ('RETURNED_TO_SUPPLIER', 'CANCELLED');

CREATE UNIQUE INDEX IF NOT EXISTS ux_adjustments_receipt_rtv
    ON adjustments (reference_type, reference_id, type)
    WHERE reference_type = 'RECEIPT' AND type = 'RETURN_TO_VENDOR';

ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS chk_audit_logs_action;

ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_action CHECK (action IN (
    'LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'STATUS_CHANGE', 'APPROVE', 'REJECT', 'CANCEL', 'SOFT_DELETE', 'ASSIGN',
    'UNASSIGN', 'UPLOAD_POD', 'REQUEST_OTP', 'CONFIRM_DELIVERY', 'RESET_DELIVERY_OTP', 'FAIL_DELIVERY',
    'TRIP_CREATE', 'TRIP_UPDATE', 'TRIP_CANCEL', 'TRIP_DEPART', 'DELIVERY_ATTEMPT_CREATE', 'COMPLETE_TRIP',
    'PICKING_PLAN_SAVE', 'PICKED_GOODS_RETURN_TO_BIN', 'PICKING_REPLACEMENT_SAVE', 'DELIVERY_ORDER_PICK_COMPLETE',
    'OUTBOUND_QC_FAIL_QUARANTINE', 'DELIVERY_ORDER_QC_APPROVE', 'DELIVERY_ORDER_WAREHOUSE_APPROVE',
    'DELIVERY_ORDER_WAREHOUSE_REJECT', 'RETURN_FLOW_RECEIVE_CONFIRM', 'RETURN_FLOW_COUNT_QC_SUBMIT',
    'RETURN_FLOW_QC_ACCEPT', 'RETURN_FLOW_QC_REJECT', 'RETURN_FLOW_PUTAWAY_PLAN', 'RETURN_FLOW_PUTAWAY_COMPLETE',
    'INVOICE_AUTO_CREATE', 'RECEIPT_RETURN_CONFIRM', 'RECEIPT_REJECT', 'RECEIPT_APPROVE', 'RECEIPT_PARTIAL_APPROVE',
    'QUARANTINE_RTV_CREATE', 'QUARANTINE_RTV_CONFIRM', 'RECEIPT_QC_CONFIRM', 'RECEIPT_QC_SUBMIT',
    'RECEIPT_PUTAWAY_COMPLETE', 'INVENTORY_UPDATE', 'TRANSFER_APPROVE', 'TRANSFER_DEPART', 'TRANSFER_UNSHIP',
    'TRANSFER_SHIP', 'TRANSFER_TRIP_ASSIGN', 'TRANSFER_SOURCE_LOAD_REPORT', 'TRANSFER_SOURCE_LOAD_REWORK',
    'TRANSFER_DISCREPANCY_CREATE', 'TRANSFER_RETURN_TO_SOURCE', 'TRANSFER_QUARANTINE_REJECT',
    'TRANSFER_FINAL_RECEIVE', 'TRANSFER_RECEIVE_CHECK', 'TRANSFER_RECEIVE_COUNT', 'TRANSFER_CANCEL',
    'TRANSFER_REJECT', 'STOCKTAKE_CANCEL', 'STOCKTAKE_REJECT', 'STOCKTAKE_APPROVE', 'STOCKTAKE_COMPLETE',
    'STOCKTAKE_AUTO_APPROVE', 'STOCKTAKE_COUNT_UPDATE', 'STOCKTAKE_START', 'STOCKTAKE_CREATE', 'PRICE_IMPORT',
    'PRICE_APPROVE', 'PRICE_CANCEL', 'PRICE_UPDATE', 'PRICE_CREATE', 'RECEIPT_CREATE',
    'RECEIPT_PRE_RECEIVE_APPROVE', 'RECEIPT_PRE_RECEIVE_REJECT', 'RECEIPT_PRE_RECEIVE_RESUBMIT',
    'RECEIPT_RECEIVE', 'RECEIPT_CANCEL', 'RECEIPT_REOPEN', 'RECEIPT_CORRECTION', 'CREDIT_NOTE_CREATE',
    'QUARANTINE_DISPOSAL_CREATE', 'QUARANTINE_DISPOSAL_APPROVE', 'VIEW_REPORT', 'TRANSFER_REQUEST_CREATE',
    'TRANSFER_REQUEST_UPDATE', 'TRANSFER_REQUEST_SUBMIT', 'TRANSFER_REQUEST_CEO_APPROVE',
    'TRANSFER_REQUEST_CEO_REJECT', 'TRANSFER_REQUEST_CONVERT', 'TRANSFER_OUTBOUND_QC', 'TRANSFER_LOAD_HANDOVER',
    'TRANSFER_ARRIVE', 'TRANSFER_ARRIVAL_HANDOVER', 'TRANSFER_RETURN_DEPART', 'TRANSFER_RETURN_ARRIVE',
    'TRANSFER_RETURN_HANDOVER', 'CORRECTION_VOUCHER_CREATE'
));
