CREATE TABLE split_delivery_plans (
    id BIGSERIAL PRIMARY KEY,
    plan_number VARCHAR(50) NOT NULL UNIQUE,
    do_id BIGINT NOT NULL REFERENCES delivery_orders(id),
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    dispatcher_id BIGINT NOT NULL REFERENCES users(id),
    lead_driver_id BIGINT NOT NULL REFERENCES drivers(id),
    status VARCHAR(30) NOT NULL DEFAULT 'PLANNED'
        CHECK (status IN ('PLANNED','IN_TRANSIT','COMPLETED','RETURNED','CANCELLED')),
    planned_start_at TIMESTAMP NOT NULL,
    departed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    cancel_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE split_delivery_legs (
    id BIGSERIAL PRIMARY KEY,
    split_plan_id BIGINT NOT NULL REFERENCES split_delivery_plans(id),
    trip_id BIGINT NOT NULL REFERENCES trips(id),
    vehicle_id BIGINT NOT NULL REFERENCES vehicles(id),
    driver_id BIGINT NOT NULL REFERENCES drivers(id),
    stop_order INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PLANNED'
        CHECK (status IN ('PLANNED','IN_TRANSIT','COMPLETED','RETURNED','CANCELLED')),
    readiness_confirmed_at TIMESTAMPTZ,
    departed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_split_delivery_legs_plan_stop UNIQUE (split_plan_id, stop_order)
);

CREATE TABLE split_delivery_leg_items (
    id BIGSERIAL PRIMARY KEY,
    split_leg_id BIGINT NOT NULL REFERENCES split_delivery_legs(id),
    do_item_id BIGINT NOT NULL REFERENCES delivery_order_items(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    batch_id BIGINT NOT NULL REFERENCES batches(id),
    quantity DECIMAL(10,2) NOT NULL CHECK (quantity > 0),
    weight_kg DECIMAL(10,2),
    volume_m3 DECIMAL(10,3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_active_split_delivery_plan_do
    ON split_delivery_plans (do_id)
    WHERE status IN ('PLANNED','IN_TRANSIT');

ALTER TABLE trip_delivery_orders
    DROP CONSTRAINT IF EXISTS trip_delivery_orders_do_id_key;

DROP INDEX IF EXISTS trip_delivery_orders_do_id_key;

ALTER TABLE trip_delivery_orders
    ADD COLUMN IF NOT EXISTS split_plan_id BIGINT REFERENCES split_delivery_plans(id);

CREATE UNIQUE INDEX IF NOT EXISTS trip_delivery_orders_do_id_key
    ON trip_delivery_orders (do_id)
    WHERE is_active = true AND split_plan_id IS NULL;

CREATE INDEX idx_split_delivery_legs_plan ON split_delivery_legs(split_plan_id);
CREATE INDEX idx_split_delivery_legs_trip ON split_delivery_legs(trip_id);
CREATE INDEX idx_split_delivery_legs_driver ON split_delivery_legs(driver_id);
CREATE INDEX idx_split_delivery_leg_items_leg ON split_delivery_leg_items(split_leg_id);
CREATE INDEX idx_split_delivery_leg_items_do_item ON split_delivery_leg_items(do_item_id);

ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS chk_audit_logs_action;

ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_action CHECK (action IN (
    'LOGIN', 'LOGOUT',
    'CREATE', 'UPDATE', 'STATUS_CHANGE',
    'APPROVE', 'REJECT', 'CANCEL', 'SOFT_DELETE',
    'ASSIGN', 'UNASSIGN',
    'VIEW_REPORT',
    'UPLOAD_POD',
    'REQUEST_OTP', 'CONFIRM_DELIVERY', 'RESET_DELIVERY_OTP', 'FAIL_DELIVERY',
    'TRIP_CREATE', 'TRIP_UPDATE', 'TRIP_CANCEL', 'TRIP_DEPART',
    'DELIVERY_ATTEMPT_CREATE', 'COMPLETE_TRIP',
    'SPLIT_DELIVERY_PLAN_CREATE', 'SPLIT_DELIVERY_PLAN_UPDATE',
    'SPLIT_DELIVERY_PLAN_CANCEL', 'SPLIT_DELIVERY_DRIVER_READY',
    'SPLIT_DELIVERY_DEPART',
    'PICKING_PLAN_SAVE', 'PICKED_GOODS_RETURN_TO_BIN',
    'PICKING_REPLACEMENT_SAVE', 'DELIVERY_ORDER_PICK_COMPLETE',
    'DELIVERY_ORDER_UPDATE',
    'OUTBOUND_QC_FAIL_QUARANTINE',
    'DELIVERY_ORDER_QC_APPROVE',
    'DELIVERY_ORDER_WAREHOUSE_APPROVE', 'DELIVERY_ORDER_WAREHOUSE_REJECT',
    'RETURN_FLOW_RECEIVE_CONFIRM',
    'RETURN_FLOW_COUNT_QC_SUBMIT',
    'RETURN_FLOW_QC_ACCEPT', 'RETURN_FLOW_QC_REJECT',
    'RETURN_FLOW_PUTAWAY_PLAN', 'RETURN_FLOW_PUTAWAY_COMPLETE',
    'INVOICE_AUTO_CREATE',
    'CREDIT_NOTE_CREATE',
    'CORRECTION_VOUCHER_CREATE',
    'RECEIPT_CREATE',
    'RECEIPT_RECEIVE', 'RECEIPT_RECEIVE_QC',
    'RECEIPT_PRE_RECEIVE_APPROVE', 'RECEIPT_PRE_RECEIVE_REJECT', 'RECEIPT_PRE_RECEIVE_RESUBMIT',
    'RECEIPT_QC_SUBMIT', 'RECEIPT_QC_CONFIRM',
    'RECEIPT_APPROVE', 'RECEIPT_PARTIAL_APPROVE', 'RECEIPT_REJECT',
    'RECEIPT_PUTAWAY_COMPLETE',
    'RECEIPT_RETURN_CONFIRM',
    'RECEIPT_CANCEL', 'RECEIPT_REOPEN', 'RECEIPT_CORRECTION',
    'QUARANTINE_RTV_CREATE', 'QUARANTINE_RTV_CONFIRM',
    'QUARANTINE_DISPOSAL_CREATE', 'QUARANTINE_DISPOSAL_APPROVE',
    'INVENTORY_UPDATE',
    'TRANSFER_REQUEST_CREATE', 'TRANSFER_REQUEST_UPDATE',
    'TRANSFER_REQUEST_SUBMIT',
    'TRANSFER_REQUEST_CEO_APPROVE', 'TRANSFER_REQUEST_CEO_REJECT',
    'TRANSFER_REQUEST_CONVERT',
    'TRANSFER_APPROVE', 'TRANSFER_REJECT', 'TRANSFER_CANCEL',
    'TRANSFER_OUTBOUND_QC',
    'TRANSFER_SOURCE_LOAD_REPORT', 'TRANSFER_SOURCE_LOAD_REWORK',
    'TRANSFER_LOAD_HANDOVER',
    'TRANSFER_TRIP_ASSIGN',
    'TRANSFER_DEPART', 'TRANSFER_SHIP', 'TRANSFER_UNSHIP',
    'TRANSFER_ARRIVE', 'TRANSFER_ARRIVAL_HANDOVER',
    'TRANSFER_RECEIVE_CHECK', 'TRANSFER_RECEIVE_COUNT',
    'TRANSFER_FINAL_RECEIVE',
    'TRANSFER_DISCREPANCY_CREATE',
    'TRANSFER_RETURN_TO_SOURCE', 'TRANSFER_QUARANTINE_REJECT',
    'TRANSFER_RETURN_DEPART', 'TRANSFER_RETURN_ARRIVE', 'TRANSFER_RETURN_HANDOVER',
    'STOCKTAKE_CREATE', 'STOCKTAKE_START',
    'STOCKTAKE_COUNT_UPDATE',
    'STOCKTAKE_COMPLETE',
    'STOCKTAKE_APPROVE', 'STOCKTAKE_AUTO_APPROVE',
    'STOCKTAKE_REJECT', 'STOCKTAKE_CANCEL',
    'PRICE_CREATE', 'PRICE_UPDATE', 'PRICE_IMPORT',
    'PRICE_APPROVE', 'PRICE_CANCEL'
));
