-- V63: Remove legacy CEO approval states from the transfer request flow.
-- Current TRQ flow is source warehouse manager approval/rejection:
-- DRAFT -> SUBMITTED -> APPROVED/REJECTED -> CONVERTED/CANCELLED.

UPDATE transfer_requests
SET status = 'APPROVED'
WHERE status = 'CEO_APPROVED';

UPDATE transfer_requests
SET status = 'REJECTED'
WHERE status = 'CEO_REJECTED';

UPDATE audit_logs
SET action = 'TRANSFER_REQUEST_SOURCE_APPROVE'
WHERE action = 'TRANSFER_REQUEST_CEO_APPROVE';

UPDATE audit_logs
SET action = 'TRANSFER_REQUEST_SOURCE_REJECT'
WHERE action = 'TRANSFER_REQUEST_CEO_REJECT';

ALTER TABLE transfer_requests
    DROP CONSTRAINT IF EXISTS transfer_requests_status_check;

ALTER TABLE transfer_requests
    ADD CONSTRAINT transfer_requests_status_check
    CHECK (status IN (
        'DRAFT',
        'SUBMITTED',
        'APPROVED',
        'REJECTED',
        'CONVERTED',
        'CANCELLED'
    ));

ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS chk_audit_logs_action;

ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_action CHECK (action IN (
    'LOGIN', 'LOGOUT',
    'CREATE', 'UPDATE', 'STATUS_CHANGE',
    'APPROVE', 'REJECT', 'CANCEL', 'SOFT_DELETE',
    'ASSIGN', 'UNASSIGN',
    'VIEW_REPORT',
    'UPLOAD_POD',
    'REQUEST_OTP', 'CONFIRM_DELIVERY', 'RESET_DELIVERY_OTP', 'FAIL_DELIVERY',
    'TRIP_CREATE', 'TRIP_UPDATE', 'TRIP_CANCEL', 'TRIP_DEPART',
    'DELIVERY_ATTEMPT_CREATE', 'COMPLETE_TRIP',
    'SPLIT_DELIVERY_PLAN_CREATE', 'SPLIT_DELIVERY_PLAN_UPDATE',
    'SPLIT_DELIVERY_PLAN_CANCEL', 'SPLIT_DELIVERY_DRIVER_READY',
    'SPLIT_DELIVERY_DEPART',
    'SPLIT_LEG_ARRIVAL_CONFIRM', 'SPLIT_LEG_HANDOVER_CONFIRM',
    'SPLIT_LEG_DELIVERY_FAIL',
    'PICKING_PLAN_SAVE', 'PICKED_GOODS_RETURN_TO_BIN',
    'PICKING_REPLACEMENT_SAVE', 'DELIVERY_ORDER_PICK_COMPLETE',
    'DELIVERY_ORDER_UPDATE',
    'OUTBOUND_QC_FAIL_QUARANTINE',
    'DELIVERY_ORDER_QC_APPROVE',
    'DELIVERY_ORDER_WAREHOUSE_APPROVE', 'DELIVERY_ORDER_WAREHOUSE_REJECT',
    'RETURN_FLOW_RECEIVE_CONFIRM',
    'RETURN_FLOW_COUNT_QC_SUBMIT',
    'RETURN_FLOW_QC_ACCEPT', 'RETURN_FLOW_QC_REJECT',
    'RETURN_FLOW_PUTAWAY_PLAN', 'RETURN_FLOW_PUTAWAY_COMPLETE',
    'INVOICE_AUTO_CREATE',
    'CREDIT_NOTE_CREATE',
    'CORRECTION_VOUCHER_CREATE',
    'RECEIPT_CREATE',
    'RECEIPT_RECEIVE', 'RECEIPT_RECEIVE_QC',
    'RECEIPT_PRE_RECEIVE_APPROVE', 'RECEIPT_PRE_RECEIVE_REJECT', 'RECEIPT_PRE_RECEIVE_RESUBMIT',
    'RECEIPT_QC_SUBMIT', 'RECEIPT_QC_CONFIRM',
    'RECEIPT_APPROVE', 'RECEIPT_PARTIAL_APPROVE', 'RECEIPT_REJECT',
    'RECEIPT_PUTAWAY_COMPLETE',
    'RECEIPT_RETURN_CONFIRM',
    'RECEIPT_CANCEL', 'RECEIPT_REOPEN', 'RECEIPT_CORRECTION',
    'RECEIPT_STOREKEEPER_REVIEW_APPROVE', 'RECEIPT_STOREKEEPER_RECOUNT_REQUEST',
    'QUARANTINE_RTV_CREATE', 'QUARANTINE_RTV_CONFIRM',
    'QUARANTINE_DISPOSAL_CREATE', 'QUARANTINE_DISPOSAL_APPROVE',
    'INVENTORY_UPDATE',
    'TRANSFER_REQUEST_CREATE', 'TRANSFER_REQUEST_UPDATE',
    'TRANSFER_REQUEST_SUBMIT',
    'TRANSFER_REQUEST_SOURCE_APPROVE', 'TRANSFER_REQUEST_SOURCE_REJECT',
    'TRANSFER_REQUEST_CONVERT',
    'TRANSFER_APPROVE', 'TRANSFER_REJECT', 'TRANSFER_CANCEL',
    'TRANSFER_OUTBOUND_QC',
    'TRANSFER_SOURCE_LOAD_REPORT', 'TRANSFER_SOURCE_LOAD_REWORK',
    'TRANSFER_LOAD_HANDOVER',
    'TRANSFER_TRIP_ASSIGN',
    'TRANSFER_DEPART', 'TRANSFER_SHIP', 'TRANSFER_UNSHIP',
    'TRANSFER_ARRIVE', 'TRANSFER_ARRIVAL_HANDOVER',
    'TRANSFER_RECEIVE_CHECK', 'TRANSFER_RECEIVE_COUNT',
    'TRANSFER_FINAL_RECEIVE',
    'TRANSFER_DISCREPANCY_CREATE',
    'TRANSFER_RETURN_TO_SOURCE', 'TRANSFER_QUARANTINE_REJECT',
    'TRANSFER_RETURN_DEPART', 'TRANSFER_RETURN_ARRIVE', 'TRANSFER_RETURN_HANDOVER',
    'STOCKTAKE_CREATE', 'STOCKTAKE_START',
    'STOCKTAKE_COUNT_UPDATE',
    'STOCKTAKE_COMPLETE',
    'STOCKTAKE_APPROVE', 'STOCKTAKE_AUTO_APPROVE',
    'STOCKTAKE_REJECT', 'STOCKTAKE_CANCEL', 'STOCKTAKE_REPORT_VIEW',
    'PRICE_CREATE', 'PRICE_UPDATE', 'PRICE_IMPORT',
    'PRICE_APPROVE', 'PRICE_CANCEL'
));
