package com.wms.enums;

public enum DeliveryOrderStatus {
    NEW,
    PICKING_PLANNED,
    WAITING_PICKING,
    PICKING,
    QC_PENDING_APPROVAL,
    QC_COMPLETED,
    WAREHOUSE_APPROVED,
    IN_TRANSIT,
    DELIVERED,
    RETURNED,
    DELIVERY_FAILED,
    COMPLETED,
    CLOSED,
    REJECTED,
    CANCELLED
}
