package com.wms.enums;

public enum SystemConfigKey {
    DEFAULT_CREDIT_LIMIT,
    DEFAULT_PAYMENT_TERM_DAYS,
    CREDIT_HOLD_OVERDUE_DAYS,
    CREDIT_UNLOCK_BUFFER_PCT,
    MONTHLY_CLOSING_DAY,
    MIN_INVENTORY_WARNING_THRESHOLD
}
