package com.wms.service.warehouse_transfer;


import com.wms.entity.access_control.*;
import com.wms.entity.audit_trail.*;
import com.wms.entity.billing_payment.*;
import com.wms.entity.dealer_management.*;
import com.wms.entity.document_numbering.*;
import com.wms.entity.driver_management.*;
import com.wms.entity.fleet_management.*;
import com.wms.entity.notification_delivery.*;
import com.wms.entity.order_fulfillment.*;
import com.wms.entity.price_management.*;
import com.wms.entity.product_catalog.*;
import com.wms.entity.stock_control.*;
import com.wms.entity.stock_counting.*;
import com.wms.entity.stock_receiving.*;
import com.wms.entity.supplier_management.*;
import com.wms.entity.user_configuration.*;
import com.wms.entity.warehouse_location.*;
import com.wms.entity.warehouse_transfer.*;
import com.wms.enums.access_control.*;
import com.wms.enums.audit_trail.*;
import com.wms.enums.billing_payment.*;
import com.wms.enums.dealer_management.*;
import com.wms.enums.driver_management.*;
import com.wms.enums.fleet_management.*;
import com.wms.enums.notification_delivery.*;
import com.wms.enums.order_fulfillment.*;
import com.wms.enums.price_management.*;
import com.wms.enums.stock_control.*;
import com.wms.enums.stock_counting.*;
import com.wms.enums.stock_receiving.*;
import com.wms.enums.supplier_management.*;
import com.wms.enums.user_configuration.*;
import com.wms.enums.warehouse_location.*;
import com.wms.enums.warehouse_transfer.*;
import com.wms.dto.request.*;
import com.wms.dto.response.InterWarehouseTransferResponse;
import com.wms.dto.response.TransferPhotoUploadResponse;
import com.wms.entity.access_control.User;
import java.util.List;
import org.springframework.web.multipart.MultipartFile;

public interface InterWarehouseTransferService {
    List<InterWarehouseTransferResponse> getAllTransfers(User actor);
    InterWarehouseTransferResponse getTransferById(Long id, User actor);
    InterWarehouseTransferResponse createTransfer(InterWarehouseTransferCreateRequest request, User actor);
    InterWarehouseTransferResponse createTransferFromApprovedRequest(InterWarehouseTransferCreateRequest request,
            User actor);
    InterWarehouseTransferResponse updateTransfer(Long id, InterWarehouseTransferUpdateRequest request, User actor);
    InterWarehouseTransferResponse cancelTransfer(Long id, InterWarehouseTransferReasonRequest request, User actor);
    InterWarehouseTransferResponse approveTransfer(Long id, User actor);
    InterWarehouseTransferResponse rejectTransfer(Long id, InterWarehouseTransferReasonRequest request, User actor);
    InterWarehouseTransferResponse assignTrip(Long id, InterWarehouseTransferTripAssignRequest request, User actor);
    InterWarehouseTransferResponse shipTransfer(Long id, User actor);
    InterWarehouseTransferResponse unshipTransfer(Long id, User actor);
    InterWarehouseTransferResponse departTransfer(Long id, User actor);
    InterWarehouseTransferResponse receiveCount(Long id, InterWarehouseTransferReceiveCountRequest request, User actor);
    InterWarehouseTransferResponse receiveCheck(Long id, InterWarehouseTransferReceiveCheckRequest request, User actor);
    InterWarehouseTransferResponse finalReceive(Long id, InterWarehouseTransferFinalReceiveRequest request, User actor);
    InterWarehouseTransferResponse returnToSource(Long id, TransferReturnRequest request, User actor);
    InterWarehouseTransferResponse quarantineReject(Long id, InterWarehouseTransferRejectRequest request, User actor);
    InterWarehouseTransferResponse requestReturn(Long id, TransferReturnRequest request, User actor);
    InterWarehouseTransferResponse approveReturn(Long id, User actor);
    InterWarehouseTransferResponse rejectReturn(Long id, TransferReturnRejectRequest request, User actor);
    InterWarehouseTransferResponse recordOutboundQc(Long id, OutboundQcRequest request, User actor);
    InterWarehouseTransferResponse loadHandover(Long id, LoadHandoverRequest request, User actor);
    InterWarehouseTransferResponse driverArrive(Long id, User actor);
    InterWarehouseTransferResponse receivingHandover(Long id, LoadHandoverRequest request, User actor);
    InterWarehouseTransferResponse returnDepart(Long id, User actor);
    InterWarehouseTransferResponse returnArrive(Long id, User actor);
    InterWarehouseTransferResponse returnHandover(Long id, LoadHandoverRequest request, User actor);
    TransferPhotoUploadResponse uploadPhotoEvidence(Long id, MultipartFile file, User actor);
}
