export const INTER_WAREHOUSE_TRANSFER_STATUS = {
  NEW: 'NEW',
  APPROVED: 'APPROVED',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_DISCREPANCY: 'COMPLETED_WITH_DISCREPANCY',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  QUARANTINED: 'QUARANTINED',
};

export const INTER_WAREHOUSE_TRANSFER_STATUS_LABELS = {
  [INTER_WAREHOUSE_TRANSFER_STATUS.NEW]: 'Mới',
  [INTER_WAREHOUSE_TRANSFER_STATUS.APPROVED]: 'Đã duyệt',
  [INTER_WAREHOUSE_TRANSFER_STATUS.IN_TRANSIT]: 'Đang vận chuyển',
  [INTER_WAREHOUSE_TRANSFER_STATUS.COMPLETED]: 'Hoàn tất',
  [INTER_WAREHOUSE_TRANSFER_STATUS.COMPLETED_WITH_DISCREPANCY]: 'Hoàn tất lệch',
  [INTER_WAREHOUSE_TRANSFER_STATUS.REJECTED]: 'Từ chối',
  [INTER_WAREHOUSE_TRANSFER_STATUS.CANCELLED]: 'Đã hủy',
  [INTER_WAREHOUSE_TRANSFER_STATUS.QUARANTINED]: 'QC lỗi - Cách ly',
};

export const interWarehouseTransferStatusLabel = (status) => INTER_WAREHOUSE_TRANSFER_STATUS_LABELS[status] || status;
