export const INTER_WAREHOUSE_TRANSFER_STATUS = {
  NEW: 'NEW',
  APPROVED: 'APPROVED',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_DISCREPANCY: 'COMPLETED_WITH_DISCREPANCY',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  QUARANTINED: 'QUARANTINED',
};

export const INTER_WAREHOUSE_TRANSFER_STATUS_LABELS = {
  [INTER_WAREHOUSE_TRANSFER_STATUS.NEW]: 'Mới',
  [INTER_WAREHOUSE_TRANSFER_STATUS.APPROVED]: 'Đã duyệt',
  [INTER_WAREHOUSE_TRANSFER_STATUS.IN_TRANSIT]: 'Đang vận chuyển',
  [INTER_WAREHOUSE_TRANSFER_STATUS.COMPLETED]: 'Hoàn tất',
  [INTER_WAREHOUSE_TRANSFER_STATUS.COMPLETED_WITH_DISCREPANCY]: 'Hoàn tất lệch',
  [INTER_WAREHOUSE_TRANSFER_STATUS.REJECTED]: 'Từ chối',
  [INTER_WAREHOUSE_TRANSFER_STATUS.CANCELLED]: 'Đã hủy',
  [INTER_WAREHOUSE_TRANSFER_STATUS.QUARANTINED]: 'QC lỗi - Cách ly',
};

export const INTER_WAREHOUSE_TRANSFER_STEP_LABELS = {
  SOURCE_LOAD_PENDING: 'Chờ công nhân xếp/báo số lượng',
  OUTBOUND_QC_PENDING: 'Chờ QC xuất',
  SOURCE_LOAD_REWORK_REQUIRED: 'Cần xử lý lại hàng xếp',
};

export const interWarehouseTransferStatusLabel = (status) => INTER_WAREHOUSE_TRANSFER_STATUS_LABELS[status] || status;

export const interWarehouseTransferStepLabel = (step) => INTER_WAREHOUSE_TRANSFER_STEP_LABELS[step] || step;
