export const TRANSFER_STATUS = {
  NEW: 'NEW',
  APPROVED: 'APPROVED',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_DISCREPANCY: 'COMPLETED_WITH_DISCREPANCY',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const TRANSFER_STATUS_LABELS = {
  [TRANSFER_STATUS.NEW]: 'Mới',
  [TRANSFER_STATUS.APPROVED]: 'Đã duyệt',
  [TRANSFER_STATUS.IN_TRANSIT]: 'Đang vận chuyển',
  [TRANSFER_STATUS.COMPLETED]: 'Hoàn tất',
  [TRANSFER_STATUS.COMPLETED_WITH_DISCREPANCY]: 'Hoàn tất lệch',
  [TRANSFER_STATUS.REJECTED]: 'Từ chối',
  [TRANSFER_STATUS.CANCELLED]: 'Đã hủy',
};

export const transferStatusLabel = (status) => TRANSFER_STATUS_LABELS[status] || status;
