package com.wms.enums.stock_receiving;


public enum ReceiptStatus {
    PENDING_MANAGER_APPROVAL,
    REVISION_REQUIRED,
    PENDING_RECEIPT,
    PENDING_STOREKEEPER_REVIEW,
    RECOUNT_REQUIRED,
    DRAFT,
    QC_COMPLETED,
    QC_FAILED,
    APPROVED,
    PARTIALLY_APPROVED,
    PUTAWAY_COMPLETED,
    RETURN_TO_SUPPLIER_PENDING,
    RETURNED_TO_SUPPLIER,
    CANCELLED
}
